In [1]:
import numpy as np 
import pandas

In [2]:
path = "Data & AI Learning Paths.xlsx"
data = pandas.read_excel(path)

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

### ImportError: Missing optional dependency 'openpyxl'. 
####  Use pip or conda to install openpyxl. !pip install opeenpyxl

#### Now the error is to install openpyxl library for reading all formats of excel and xml etc files

In [1]:
import pandas as pd

path = "Data & AI Learning Paths.xlsx"
try:            # try printing head if it works
    data = pd.read_excel(path, engine='openpyxl')
    print(data.head())
except Exception as e: # else show error
    print(f"Error: {e}")

   Unnamed: 0            Unnamed: 1  \
0         NaN  Python Learning Path
1         NaN                     #
2         NaN                     1
3         NaN                     2
4         NaN                     3

                                          Unnamed: 2
0                                                NaN
1                                             Module
2  Introduction to Python - Training | Microsoft ...
3  Python for beginners - Training | Microsoft Learn
4      Get started with Python in Visual Studio Code

In [2]:
path = "Data & AI Learning Paths.xlsx"
data = pd.read_excel(path)

In [3]:
df = data.copy() # data copied to new variable to prevent data to be in same original condition

In [4]:
df1 = pd.DataFrame(df) # data converted to data frame

In [5]:
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,NaN,Python Learning Path,NaN
1,NaN,#,Module
2,NaN,1,Introduction to Python - Training | Microsoft ...
3,NaN,2,Python for beginners - Training | Microsoft Learn
4,NaN,3,Get started with Python in Visual Studio Code
5,NaN,4,Create and manage projects in Python
6,NaN,5,Numpy
7,NaN,6,Pandas
8,NaN,7,Scipy
9,NaN,8,File handling
10,NaN,9,Requests
11,NaN,10,Using GitHub Copilot with Python
12,NaN,11,Explore and analyze data with Python
13,NaN,12,Manage data with Python dictionaries
14,NaN,13,Get started with Jupyter notebooks for Python
15,NaN,14,Build an AI web app by using Python and Flask ...
16,NaN,15,Introduction to object-oriented programming wi...
17,NaN,16,Python error handling
18,NaN,17,Deploy a Django application to Azure by using ...
19,NaN,18,Python Glossary

In [6]:
df1.isnull().sum()

Unnamed: 0    20
Unnamed: 1     0
Unnamed: 2     1
dtype: int64

In [7]:
df1.isnull()

    Unnamed: 0  Unnamed: 1  Unnamed: 2
0         True       False        True
1         True       False       False
2         True       False       False
3         True       False       False
4         True       False       False
5         True       False       False
6         True       False       False
7         True       False       False
8         True       False       False
9         True       False       False
10        True       False       False
11        True       False       False
12        True       False       False
13        True       False       False
14        True       False       False
15        True       False       False
16        True       False       False
17        True       False       False
18        True       False       False
19        True       False       False

In [8]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2'], dtype='object')

In [18]:
df1.dropna(axis=1)
df1

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,NaN,Python Learning Path,NaN
1,NaN,#,Module
2,NaN,1,Introduction to Python - Training | Microsoft ...
3,NaN,2,Python for beginners - Training | Microsoft Learn
4,NaN,3,Get started with Python in Visual Studio Code
5,NaN,4,Create and manage projects in Python
6,NaN,5,Numpy
7,NaN,6,Pandas
8,NaN,7,Scipy
9,NaN,8,File handling
10,NaN,9,Requests
11,NaN,10,Using GitHub Copilot with Python
12,NaN,11,Explore and analyze data with Python
13,NaN,12,Manage data with Python dictionaries
14,NaN,13,Get started with Jupyter notebooks for Python
15,NaN,14,Build an AI web app by using Python and Flask ...
16,NaN,15,Introduction to object-oriented programming wi...
17,NaN,16,Python error handling
18,NaN,17,Deploy a Django application to Azure by using ...
19,NaN,18,Python Glossary

In [22]:
dff = df1.drop(columns=['Unnamed: 0'])

In [23]:
dff.fillna("None")

              Unnamed: 1                                         Unnamed: 2
0   Python Learning Path                                               None
1                      #                                             Module
2                      1  Introduction to Python - Training | Microsoft ...
3                      2  Python for beginners - Training | Microsoft Learn
4                      3      Get started with Python in Visual Studio Code
5                      4               Create and manage projects in Python
6                      5                                              Numpy
7                      6                                             Pandas
8                      7                                              Scipy
9                      8                                      File handling
10                     9                                           Requests
11                    10                   Using GitHub Copilot with Python
12                    11               Explore and analyze data with Python
13                    12               Manage data with Python dictionaries
14                    13      Get started with Jupyter notebooks for Python
15                    14  Build an AI web app by using Python and Flask ...
16                    15  Introduction to object-oriented programming wi...
17                    16                              Python error handling
18                    17  Deploy a Django application to Azure by using ...
19                    18                                    Python Glossary

In [25]:
dff.iloc[1:1] = "none"

In [27]:
dff.columns

Index(['Unnamed: 1', 'Unnamed: 2'], dtype='object')

In [28]:
dff.describe()

                  Unnamed: 1 Unnamed: 2
count                     20         19
unique                    20         19
top     Python Learning Path     Module
freq                       1          1

In [29]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 1  20 non-null     object
 1   Unnamed: 2  19 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes

In [31]:
df2 = data.copy()
df2.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,NaN,Python Learning Path,NaN
1,NaN,#,Module
2,NaN,1,Introduction to Python - Training | Microsoft ...
3,NaN,2,Python for beginners - Training | Microsoft Learn
4,NaN,3,Get started with Python in Visual Studio Code

In [36]:
df_2 = df2.to_csv()
df_2

',Unnamed: 0,Unnamed: 1,Unnamed: 2\r\n0,,Python Learning Path,\r\n1,,#,Module\r\n2,,1,Introduction to Python - Training | Microsoft Learn\r\n3,,2,Python for beginners - Training | Microsoft Learn\r\n4,,3,Get started with Python in Visual Studio Code\r\n5,,4,Create and manage projects in Python\r\n6,,5,Numpy\r\n7,,6,Pandas\r\n8,,7,Scipy\r\n9,,8,File handling\r\n10,,9,Requests\r\n11,,10,Using GitHub Copilot with Python\r\n12,,11,Explore and analyze data with Python\r\n13,,12,Manage data with Python dictionaries\r\n14,,13,Get started with Jupyter notebooks for Python\r\n15,,14,Build an AI web app by using Python and Flask - Training | Microsoft Learn\r\n16,,15,Introduction to object-oriented programming with Python - Training | Microsoft Learn\r\n17,,16,Python error handling\r\n18,,17,Deploy a Django application to Azure by using PostgreSQL - Training | Microsoft Learn\r\n19,,18,Python Glossary\r\n'

In [41]:
print(df_2)

,Unnamed: 0,Unnamed: 1,Unnamed: 2
0,,Python Learning Path,
1,,#,Module
2,,1,Introduction to Python - Training | Microsoft Learn
3,,2,Python for beginners - Training | Microsoft Learn
4,,3,Get started with Python in Visual Studio Code
5,,4,Create and manage projects in Python
6,,5,Numpy
7,,6,Pandas
8,,7,Scipy
9,,8,File handling
10,,9,Requests
11,,10,Using GitHub Copilot with Python
12,,11,Explore and analyze data with Python
13,,12,Manage data with Python dictionaries
14,,13,Get started with Jupyter notebooks for Python
15,,14,Build an AI web app by using Python and Flask - Training | Microsoft Learn
16,,15,Introduction to object-oriented programming with Python - Training | Microsoft Learn
17,,16,Python error handling
18,,17,Deploy a Django application to Azure by using PostgreSQL - Training | Microsoft Learn
19,,18,Python Glossary

In [42]:
# Read the CSV file into a pandas DataFrame
df_two = pd.read_csv(df_2)

df_two

FileNotFoundError: [Errno 2] No such file or directory: ',Unnamed: 0,Unnamed: 1,Unnamed: 2\r\n0,,Python Learning Path,\r\n1,,#,Module\r\n2,,1,Introduction to Python - Training | Microsoft Learn\r\n3,,2,Python for beginners - Training | Microsoft Learn\r\n4,,3,Get started with Python in Visual Studio Code\r\n5,,4,Create and manage projects in Python\r\n6,,5,Numpy\r\n7,,6,Pandas\r\n8,,7,Scipy\r\n9,,8,File handling\r\n10,,9,Requests\r\n11,,10,Using GitHub Copilot with Python\r\n12,,11,Explore and analyze data with Python\r\n13,,12,Manage data with Python dictionaries\r\n14,,13,Get started with Jupyter notebooks for Python\r\n15,,14,Build an AI web app by using Python and Flask - Training | Microsoft Learn\r\n16,,15,Introduction to object-oriented programming with Python - Training | Microsoft Learn\r\n17,,16,Python error handling\r\n18,,17,Deploy a Django application to Azure by using PostgreSQL - Training | Microsoft Learn\r\n19,,18,Python Glossary\r\n'